### ISSUE TITLE
Unable to migrate from rocks to sqlite

### ISSUE THREAD

**Issue by ogarcia** [ShadowJonathan/conduit_toolbox#12]
I was trying to use this tool to move my conduit database from rocksdb to sqlite and it does not work correctly. I get the following error:
```sh
% conduit_migrate -f rocks -t sqlite -s conduit -d exit
[tools/migrate/src/main.rs:164:5] &src_dir = "/home/user/conduit"
[tools/migrate/src/main.rs:164:5] &dst_dir = "/home/user/exit"
Error: Corruption: unknown checksum type 4 from footer of /home/user/conduit/006562.sst, while checking block at offset 1035 size 79
```

It seems as if there is a problem with that particular file, however conduit does not complain about any database problems.

**Comment by ShadowJonathan** [comment]
I'm unsure, is conduit using a newer version of the library or the likes?

**Comment by ogarcia** [comment]
I wouldn't know, right now I'm using [conduit 0.7.0](https://gitlab.com/famedly/conduit/-/releases/v0.7.0). When I did the test I was with a version of the master between 0.6.0 and 0.7.0.

**Comment by ShadowJonathan** [comment]
@ogarcia I've just updated the toolbox, which likely fixed this error. Do you want to check again, or just close the issue as-is?

**Comment by ogarcia** [comment]
@ShadowJonathan seens fixed. At least it does not give error and seems to migrate correctly from rocks to sqlite. Thanks!!!
